#!/bin/bash
for i in `find . -maxdepth 1 -mindepth 1 -type d`
do 
echo '_______________________'
cd $i
for j in `find . -maxdepth 1 -mindepth 1 -type f`
do
rm annotations.txt
gunzip $j
done
for j1 in `find . -maxdepth 1 -mindepth 1 -type f`
do
mv $j1 ../
done
cd ..
rm -r $i
done
rm MANIFEST.txt
